# Generated by Django 3.0.8 on 2021-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileandFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.BigIntegerField(unique=True)),
                ('typee', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('eof', models.BooleanField()),
                ('next_Slice', models.IntegerField(null=True)),
            ],
        ),
    ]
