# Generated by Django 3.0.8 on 2021-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileandfolder',
            name='directory',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
