# Generated by Django 3.0.8 on 2021-06-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210620_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileandfolder',
            old_name='directory',
            new_name='existingPath',
        ),
        migrations.RemoveField(
            model_name='fileandfolder',
            name='next_Slice',
        ),
        migrations.RemoveField(
            model_name='fileandfolder',
            name='typee',
        ),
    ]
