# Generated by Django 3.0.8 on 2021-06-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20210620_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileandFolder',
            new_name='File',
        ),
    ]
